
vector_desc_call_logs = [
    'nz ratio daily calls',
    'mean daily calls',
    'std daily calls',
    'qn scale daily calls',
    'mean unique daily calls',
    'std unique daily calls',
    'mean duration daily calls',
    'std duration daily calls',
    'mean repetitive daily calls',
    'std repetitive daily calls',
    'nz daily incoming calls ratio',
    'mean daily incoming calls',
    'std daily incoming calls',
    'qn scale daily incoming calls',
    'mean unique daily incoming calls',
    'std unique daily incoming calls',
    'mean duration daily incoming calls',
    'std duration daily incoming calls',
    'mean repetitive daily incoming calls',
    'std repetitive daily incoming calls',
    'nz daily outgoing calls ratio',
    'mean daily outgoing calls',
    'std daily outgoing calls',
    'qn scale daily outgoing calls',
    'mean unique daily outgoing calls',
    'std unique daily outgoing calls',
    'mean duration daily outgoing calls',
    'std duration daily outgoing calls',
    'mean repetitive daily outgoing calls',
    'std repetitive daily outgoing calls',
    'nz daily missed ratio',
    'mean daily missed calls',
    'std daily missed calls',
    'qn scale daily missed calls',
    'nz night calls ratio',
    'mean nightly calls',
    'std nightly calls',
    'qn scale nightly calls',
    'mean unique nightly calls',
    'std unique nightly calls',
    'mean duration nightly calls',
    'std duration nightly calls',
    'mean repetitive nightly calls',
    'std repetitive nightly calls',
    'nz weekend calls ratio',
    'mean weekend calls',
    'std weekend calls',
    'qn scale weekend calls',
    'mean unique weekend calls',
    'std unique weekend calls',
    'mean duration weekend calls',
    'std duration weekend calls',
    'mean repetitive weekend calls',
    'std repetitive weekend calls',
    'ratio of response to incoming calls',
    'ratio of response to outgoing calls',
    'entropy by duration calls',
    'entropy by duration incoming calls',
    'entropy by duration outgoing calls',
    'entropy by frequency calls',
    'entropy by frequency incoming calls',
    'entropy by frequency outgoing calls',
    'entropy by number calls',
    'entropy by number incoming calls',
    'entropy by number outgoing calls',
    'ar daily num of calls lag-1',
    'ar daily num of calls lag-4',
    'ar daily num of calls lag-8',
    'ar daily num of calls lag-16',
    'ar daily mean dur of calls lag-1',
    'ar daily mean dur of calls lag-4',
    'ar daily mean dur of calls lag-8',
    'ar daily mean dur of calls lag-16',
    'ivi irregularity daily number calls',
    'ivi irregularity daily duration calls',
    'ivi irr daily mean delta between calls',
    'ivi irregularity daily night calls',
    'ivi irregularity daily number incoming calls',
    'ivi irregularity daily number outgoing calls'
]

vector_desc_photo_gallery = [
    'median daily number photos - location',
    'mad daily number photos - scale',
    'mean number of photos in burst',
    'median number of photos in burst',
    'median number of bursts a week',
    'mad number of bursts a week',
    'median night time number photos',
    'mad night time number photos',
    'median day time number photos',
    'mad day time number photos',
    'median weekend number photos',
    'mad weekend number photos',
    'median work days number photos',
    'mad work days number photos',
    'ar daily num of photos lag-1',
    'entropy on daily photos'
]

vector_desc_installed_apps = [
    'mean max ratio of category of installed apps',
    'median max ratio of category of installed apps',
    'app category coverage ratio',
    'entropy of app categories',
    'entropy of install app time of day'
]
