
vector_desc_call_logs = [
    'nz ratio daily calls',
    'mean daily calls',
    'std daily calls',
    'mad daily calls',
    'mean unique daily calls',
    'std unique daily calls',
    #'mad unique daily calls',
    'nz ratio daily duration',
    'mean duration daily calls',
    'std duration daily calls',
    'mad duration daily calls',
    'mean repetitive daily calls',
    'std repetitive daily calls',
    'nz daily incoming calls ratio',
    'mean daily incoming calls',
    'std daily incoming calls',
    'mad daily incoming calls',
    'mean unique daily incoming calls',
    'std unique daily incoming calls',
    #'mad unique daily incoming calls',
    'mean duration daily incoming calls',
    'std duration daily incoming calls',
    'mad duration daily incoming calls',
    'nz daily outgoing calls ratio',
    'mean daily outgoing calls',
    'std daily outgoing calls',
    'mad daily outgoing calls',
    'mean unique daily outgoing calls',
    'std unique daily outgoing calls',
    #'mad unique daily outgoing calls',
    'mean duration daily outgoing calls',
    'std duration daily outgoing calls',
    'mad duration daily outgoing calls',
    'nz daily missed ratio',
    'mean daily missed calls',
    'std daily missed calls',
    'mad daily missed calls',
    'mean unique daily missed calls',
    'std unique daily missed calls',
    #'mad unique daily missed calls',
    'nz night calls ratio',
    'mean nightly calls',
    'std nightly calls',
    'mad nightly calls',
    'mean unique nightly calls',
    'std unique nightly calls',
    #'mad unique nightly calls',
    'nz_night_incoming_calls_ratio',
    'mean nightly incoming calls',
    'std nightly incoming calls',
    'mad nightly incoming calls',
    'mean duration nightly incoming calls',
    'std duration nightly incoming calls',
    'mad duration nightly incoming calls',
    'nz night outgoing calls ratio',
    'mean nightly outgoing calls',
    'std nightly outgoing calls',
    'mad nightly outgoing calls',
    'mean duration nightly outgoing calls',
    'std duration nightly outgoing calls',
    'mad duration nightly outgoing calls',
    'nz night missed calls ratio',
    'mean nightly missed calls',
    'std nightly missed calls',
    'mad nightly missed calls',
    'nz weekend calls ratio',
    'mean weekend calls',
    'std weekend calls',
    'mad weekend calls',
    'nz weekend duration ratio',
    'mean duration weekend calls',
    'std duration weekend calls',
    'mad duration weekend calls',
    'mean unique weekend calls',
    'std unique weekend calls',
    #'mad unique weekend calls',
    'mean repetitive weekend calls',
    'std repetitive weekend calls',
    'ratio of response to incoming calls',
    'ratio of response to outgoing calls',
    'entropy by duration incoming calls',
    'entropy by duration outgoing calls',
    'entropy by frequency incoming calls',
    'entropy by frequency outgoing calls',
    'entropy by number incoming calls',
    'entropy by number outgoing calls',
    #'is daily num of calls stationary',
    'ar daily num of calls lag-1',
    'ar daily num of calls lag-4',
    'ar daily num of calls lag-16',
    #'is daily dur of calls stationary',
    'ar daily mean dur of calls lag-1',
    'ar daily mean dur of calls lag-4',
    'ar daily mean dur of calls lag-16',
    'ivi irregularity daily number calls',
    'ivi irregularity daily duration calls',
    'ivi irr daily mean delta between calls',
    'ivi irregularity daily night calls',
    'ivi irregularity daily number incoming calls',
    'ivi irregularity daily number outgoing calls'
    #'ivi irregularity daily number missed calls'
]

vector_desc_photo_gallery = [
    'mean daily number photos',
    'std daily number photos',
    'mad daily number photos',
    'mean daily unique format',
    'std daily unique format',
    'min ratio of photos by category',
    'max ratio of photos by category',
    'mean weekend number photos',
    'std weekend number photos',
    'mad weekend number photos',
    'mean nightly number photos',
    'std nightly number photos',
    'mad nightly number photos',
    'is daily mean num of photos stationary',
    'ar daily num of photos lag-1',
    'ar daily num of photos lag-4',
    'ar daily num of photos lag-16',
    #'entropy on photo category',
    'ivi irregularity on photos per day',
    'ivi irregularity on time between photos'
]
vector_desc_installed_apps = [
    'mean monthly installed apps',
    'std monthly installed apps',
    'min monthly installed app',
    'max monthly installed app',
    'min installed category',
    'max installed category',
    'percentage of min installed category',
    'percentage of max installed category',
    'mean days between installs',
    'std days between installs',
    'min days between installs',
    'max days between installs',
    'percentage of apps install in day time',
    'percentage of apps install in night time',
    'percentage of apps install in weekend',
    'min category free app installed',
    'max category free app installed',
    'min category paid app installed',
    'max category paid app installed',
    'percentage of free installed app',
    'percentage of paid installed app',
    'entropy of app categories'
]